#!/usr/bin/env bash

PUBLIC_FOLDER=public-artifacts

cat Configs/ClashMeta.yaml |
    sed 's|https://gist\.githubusercontent\.com/aur3l14no.*|https://cp.cloudflare.com/generate_204|g' \
    > public-artifacts/Configs/ClashMeta.yaml

diff Configs/ClashMeta.yaml ${PUBLIC_FOLDER}/Configs/ClashMeta.yaml
