#!/usr/bin/env bash

PUBLIC_FOLDER=public-artifacts
LOCAL_PATH="${HOME}/.config/clash-meta/ClashMeta.yaml"

sed 's/".*"\s*#\s*SECRET/""/' "${LOCAL_PATH}" \
    > public-artifacts/Configs/ClashMeta.yaml

diff "${LOCAL_PATH}" ${PUBLIC_FOLDER}/Configs/ClashMeta.yaml
