mixed-port: 7890
ipv6: true
log-level: info
external-controller: 127.0.0.1:9090

find-process-mode: strict

mode: rule

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

proxy-providers:
  provider:
    type: http
    url: https://cp.cloudflare.com/generate_204
    interval: 3600
    path: ./provider.yaml
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204
  provider-fixed-ss:
    type: http
    url: https://cp.cloudflare.com/generate_204
    interval: 3600
    path: ./provider_fixed_ss.yaml
    dialer-proxy: Fastest-ALL
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204

proxy-groups:
  - name: Proxy
    type: select
    use:
      - provider
    proxies:
      - Fastest-ALL
      - Fixed-Default

  - name: Fixed-Default
    type: select
    use:
      - provider
      - provider-fixed-ss
    filter: \[自建(SS)?\]

  - name: Fixed-US
    type: select
    filter: (?i)\[自建(SS)?].*(US|美国)
    use:
      - provider
      - provider-fixed-ss

  - name: Fastest-ALL
    type: url-test
    use:
      - provider
    url: "https://cp.cloudflare.com/generate_204"
    interval: 600
    tolerance: 100

  - name: Fastest-US
    type: url-test
    filter: (?i)US|美国
    use:
      - provider
    url: "https://cp.cloudflare.com/generate_204"
    interval: 600
    tolerance: 100

  - name: Fastest-JP
    type: url-test
    filter: (?i)JP|日本
    use:
      - provider
    url: "https://cp.cloudflare.com/generate_204"
    interval: 600
    tolerance: 100

  - name: OpenAI
    type: fallback
    proxies:
      - Fixed-US
      - Fastest-US

  - name: Fallback
    type: select
    proxies:
      - Proxy
      - DIRECT

rule_provider_conf: &rule_provider_conf
  interval: 259200 # 3d
  type: http

rule-providers:
  fish-direct:
    path: ./rules/fish-direct.yaml
    behavior: classical
    url: https://raw.githubusercontent.com/aur3l14no/fish-sia/main/public-artifacts/Rules/Clash/direct.yaml
    <<: *rule_provider_conf
  OpenAI:
    path: ./rules/OpenAI.yaml
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
    <<: *rule_provider_conf
  ChinaMax_Domain:
    path: ./rules/ChinaMax_Domain.yaml
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml
    <<: *rule_provider_conf
  ChinaMax:
    path: ./rules/ChinaMax.yaml
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.yaml
    <<: *rule_provider_conf
  Global_Domain:
    path: ./rules/Global_Domain.yaml
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Domain.yaml
    <<: *rule_provider_conf
  Global:
    path: ./rules/Global.yaml
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml
    <<: *rule_provider_conf
  Advertising_domain:
    path: ./rules/Advertising_domain.yaml
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml
    <<: *rule_provider_conf
  Advertising:
    path: ./rules/Advertising.yaml
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml
    <<: *rule_provider_conf

rules:
  - RULE-SET,fish-direct,DIRECT
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,ChinaMax_Domain,DIRECT
  - RULE-SET,ChinaMax,DIRECT
  - RULE-SET,Global_Domain,Proxy
  - RULE-SET,Global,Proxy
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Fallback
